import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { LifeCounterProvider } from "./context/LifeCounterContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="font-bold font-sans text-[19px] fixed left-0 top-0 z-[1] pointer-events-none">
          Instance: {process.env.NEXT_PUBLIC_INSTANCE}
        </div>
        <LifeCounterProvider>
          {children}
        </LifeCounterProvider> 
      </body>
    </html>
  );
}
